export { createDb, type Database } from './client.js';
export {
  auditLogs,
  authorizationCodes,
  challengeTypeEnum,
  consentGrants,
  emailVerificationTokenColumns,
  emailVerificationTokens,
  loginAttempts,
  mfaChallenges,
  oauthClientColumns,
  oauthClients,
  parRequests,
  passkeyColumns,
  passkeys,
  passwordResetTokens,
  permissions,
  recoveryCodes,
  refreshTokens,
  rolePermissions,
  roles,
  sessionColumns,
  sessions,
  signingKeyColumns,
  signingKeys,
  totpSecretColumns,
  totpSecrets,
  userColumns,
  userRoles,
  users,
  webauthnChallenges,
} from './schema/index.js';
